language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
script:
   - xctool -project asimplechessgame.xcodeproj -scheme 'GCov' test -configuration Debug -sdk iphonesimulator -arch i386 build
after_success:
  - coveralls -x '.m' --exclude Apptimize.framework --exclude lib --exclude tests